In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('data/train_sessions.csv', index_col='session_id')
data.head()

site1                time1  site2                time2    site3  \
session_id                                                                    
1             718  2014-02-20 10:02:45    NaN                  NaN      NaN   
2             890  2014-02-22 11:19:50  941.0  2014-02-22 11:19:50   3847.0   
3           14769  2013-12-16 16:40:17   39.0  2013-12-16 16:40:18  14768.0   
4             782  2014-03-28 10:52:12  782.0  2014-03-28 10:52:42    782.0   
5              22  2014-02-28 10:53:05  177.0  2014-02-28 10:55:22    175.0   

                          time3    site4                time4  site5  \
session_id                                                             
1                           NaN      NaN                  NaN    NaN   
2           2014-02-22 11:19:51    941.0  2014-02-22 11:19:51  942.0   
3           2013-12-16 16:40:19  14769.0  2013-12-16 16:40:19   37.0   
4           2014-03-28 10:53:12    782.0  2014-03-28 10:53:42  782.0   
5           2014-02-28 10:55:22    178.0  2014-02-28 10:55:23  177.0   

                          time5  ...                  time6    site7  \
session_id                       ...                                   
1                           NaN  ...                    NaN      NaN   
2           2014-02-22 11:19:51  ...    2014-02-22 11:19:51   3847.0   
3           2013-12-16 16:40:19  ...    2013-12-16 16:40:19  14768.0   
4           2014-03-28 10:54:12  ...    2014-03-28 10:54:42    782.0   
5           2014-02-28 10:55:23  ...    2014-02-28 10:55:59    175.0   

                          time7    site8                time8    site9  \
session_id                                                               
1                           NaN      NaN                  NaN      NaN   
2           2014-02-22 11:19:52   3846.0  2014-02-22 11:19:52   1516.0   
3           2013-12-16 16:40:20  14768.0  2013-12-16 16:40:21  14768.0   
4           2014-03-28 10:55:12    782.0  2014-03-28 10:55:42    782.0   
5           2014-02-28 10:55:59    177.0  2014-02-28 10:55:59    177.0   

                          time9   site10               time10 target  
session_id                                                            
1                           NaN      NaN                  NaN      0  
2           2014-02-22 11:20:15   1518.0  2014-02-22 11:20:16      0  
3           2013-12-16 16:40:22  14768.0  2013-12-16 16:40:24      0  
4           2014-03-28 10:56:12    782.0  2014-03-28 10:56:42      0  
5           2014-02-28 10:57:06    178.0  2014-02-28 10:57:11      0  

[5 rows x 21 columns]

In [3]:
data.info(verbose=True, null_counts=True)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 253561 entries, 1 to 253561
Data columns (total 21 columns):
site1     253561 non-null int64
time1     253561 non-null object
site2     250098 non-null float64
time2     250098 non-null object
site3     246919 non-null float64
time3     246919 non-null object
site4     244321 non-null float64
time4     244321 non-null object
site5     241829 non-null float64
time5     241829 non-null object
site6     239495 non-null float64
time6     239495 non-null object
site7     237297 non-null float64
time7     237297 non-null object
site8     235224 non-null float64
time8     235224 non-null object
site9     233084 non-null float64
time9     233084 non-null object
site10    231052 non-null float64
time10    231052 non-null object
target    253561 non-null int64
dtypes: float64(9), int64(2), object(10)
memory usage: 42.6+ MB


In [4]:
data.shape

(253561, 21)

In [5]:
data['target'].value_counts()

0    251264
1      2297
Name: target, dtype: int64

In [6]:
site_columns = ['site1', 'site2', 'site3', 'site4', 'site5', 'site6', 'site7', 'site8', 'site9', 'site10']
sites_set = set()
for col in site_columns:
    current_set = set(data[data[col].notna()][col].astype(int).unique())
    sites_set = sites_set.union(current_set)

len(sites_set), min(sites_set), max(sites_set)

(41601, 1, 41601)

In [18]:
data[site_columns] = data[site_columns].fillna(0).astype(int)

In [19]:
data.head()

site1                time1  site2                time2  site3  \
session_id                                                                  
1             718  2014-02-20 10:02:45      0                  NaN      0   
2             890  2014-02-22 11:19:50    941  2014-02-22 11:19:50   3847   
3           14769  2013-12-16 16:40:17     39  2013-12-16 16:40:18  14768   
4             782  2014-03-28 10:52:12    782  2014-03-28 10:52:42    782   
5              22  2014-02-28 10:53:05    177  2014-02-28 10:55:22    175   

                          time3  site4                time4  site5  \
session_id                                                           
1                           NaN      0                  NaN      0   
2           2014-02-22 11:19:51    941  2014-02-22 11:19:51    942   
3           2013-12-16 16:40:19  14769  2013-12-16 16:40:19     37   
4           2014-03-28 10:53:12    782  2014-03-28 10:53:42    782   
5           2014-02-28 10:55:22    178  2014-02-28 10:55:23    177   

                          time5  ...                  time6  site7  \
session_id                       ...                                 
1                           NaN  ...                    NaN      0   
2           2014-02-22 11:19:51  ...    2014-02-22 11:19:51   3847   
3           2013-12-16 16:40:19  ...    2013-12-16 16:40:19  14768   
4           2014-03-28 10:54:12  ...    2014-03-28 10:54:42    782   
5           2014-02-28 10:55:23  ...    2014-02-28 10:55:59    175   

                          time7  site8                time8  site9  \
session_id                                                           
1                           NaN      0                  NaN      0   
2           2014-02-22 11:19:52   3846  2014-02-22 11:19:52   1516   
3           2013-12-16 16:40:20  14768  2013-12-16 16:40:21  14768   
4           2014-03-28 10:55:12    782  2014-03-28 10:55:42    782   
5           2014-02-28 10:55:59    177  2014-02-28 10:55:59    177   

                          time9 site10               time10 target  
session_id                                                          
1                           NaN      0                  NaN      0  
2           2014-02-22 11:20:15   1518  2014-02-22 11:20:16      0  
3           2013-12-16 16:40:22  14768  2013-12-16 16:40:24      0  
4           2014-03-28 10:56:12    782  2014-03-28 10:56:42      0  
5           2014-02-28 10:57:06    178  2014-02-28 10:57:11      0  

[5 rows x 21 columns]

In [22]:
sites_bag = pd.get_dummies(data, columns=site_columns, sparse=True)

In [23]:
type(sites_bag)

pandas.core.sparse.frame.SparseDataFrame

In [25]:
sites_bag.shape

(253561, 157773)

In [28]:
del sites_bag

In [30]:
data[site_columns].head()

site1  site2  site3  site4  site5  site6  site7  site8  site9  \
session_id                                                                  
1             718      0      0      0      0      0      0      0      0   
2             890    941   3847    941    942   3846   3847   3846   1516   
3           14769     39  14768  14769     37     39  14768  14768  14768   
4             782    782    782    782    782    782    782    782    782   
5              22    177    175    178    177    178    175    177    177   

            site10  
session_id          
1                0  
2             1518  
3            14768  
4              782  
5              178

In [34]:
data[site_columns].values.flatten().shape

(2535610,)

In [35]:
from scipy.sparse import csr_matrix

In [39]:
csr_matrix(([1,2,3,4], ([0, 1, 2, 0], [0, 2, 1, 2]))).toarray()

array([[1, 0, 4],
       [0, 0, 2],
       [0, 3, 0]])

In [48]:
csr_matrix(([1,2,3,4], [0,2,1,3], [0,2,3,4])).toarray()

array([[1, 0, 2, 0],
       [0, 3, 0, 0],
       [0, 0, 0, 4]])

In [57]:
csr_matrix(([1,2,4,8], [0,1,1,2], [0,1,3])).toarray()

array([[1, 0, 0],
       [0, 6, 0]])

In [58]:
flat_data = data[site_columns].values.flatten()
csr_data = csr_matrix(([1]*flat_data.shape[0], flat_data, range(0,flat_data.shape[0]+10,10)))
csr_data.shape

(253561, 41602)

In [65]:
csr_data[0].nonzero()

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32),
 array([718,   0,   0,   0,   0,   0,   0,   0,   0,   0], dtype=int32))

In [60]:
del flat_data

In [66]:
csr_data[0,0]

9